# cicd pipeline
steps:
  - name: 'node:14'
    entrypoint: 'npm'
    args: ['install']
    id: 'install'

  - name: 'node:14'
    entrypoint: 'npm'
    args: ['run', 'test:coverage']
    id: 'create coverage report'

  # - name: 'gcr.io/cloud-builders/docker'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |              
  #       docker run --rm -e SONAR_HOST_URL="https://sonarcloud.io/" \
  #         -e SONAR_SCANNER_OPTS="-Dsonar.projectKey=${_PROJECT_KEY} -Dsonar.organization=${_ORGANIZATION} \
  #         -Dsonar.sources=. -Dsonar.python.coverage.reportPaths=/usr/src/coverage.xml" \
  #         -e SONAR_TOKEN=$$sonarcloud_token \
  #         -v "/workspace:/usr/src" \
  #         sonarsource/sonar-scanner-cli
  #   secretEnv: ['sonarcloud_token']
  #   id: 'sonarcloud scanning'
# availableSecrets:
#   secretManager: 
#   - versionName: projects/$PROJECT_ID/secrets/sonarcloud_token
#     env: 'sonarcloud_token'
# substitutions:
#   _PROJECT_KEY: scalaproject
#   _ORGANIZATION: merinaphilip
options:
  logging: "CLOUD_LOGGING_ONLY"
